[
    {
    CustomerID: 1001,
    Name: 'Nirav Joshi',
    CustomerEmail: 'nirav@gmail.com',
    Photo: "./imgs/avatar2.jpg",
    ProjectName: 'Hosting Press HTML',
    Status: 'Active',
    Weeks: '40',
    Budget: '$2.4k',
    Location: 'India',
    },
    {
    CustomerID: 1002,
    Name: 'Sunil Joshi',
    CustomerEmail: 'sunil@gmail.com',
    ProjectName: 'Elite Admin',
    Status: 'Active',
    Photo: "./imgs/avatar3.png",
    Weeks: '11',
    Budget: '$3.9k',
    Location: 'India',
    },
    {
    CustomerID: 1003,
    Name: 'Andrew McDownland',
    CustomerEmail: 'andrew@gmail.com',
    ProjectName: 'Real Homes WP Theme',
    Status: 'Pending',
    Photo: "./imgs/avatar4.jpg",
    Weeks: '19',
    Budget: '$24.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1004,
    Name: 'Christopher Jamil',
    CustomerEmail: 'jamil@gmail.com',
    ProjectName: 'MedicalPro WP Theme',
    Status: 'Completed',
    Photo: "./imgs/avatar.jpg",
    Weeks: '34',
    Budget: '$16.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1005,
    Name: 'Michael',
    CustomerEmail: 'michael@gmail.com',
    ProjectName: 'Weekly WP Theme',
    Status: 'Cancel',
    Photo: "./imgs/avatar2.jpg",
    Weeks: '34',
    Budget: '$16.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1006,
    Name: 'Nirav Joshi',
    CustomerEmail: 'nirav@gmail.com',
    Photo: "./imgs/avatar2.jpg",
    ProjectName: 'Hosting Press HTML',
    Status: 'Active',
    Weeks: '40',
    Budget: '$2.4k',
    Location: 'India',
    },
    {
    CustomerID: 1007,
    Name: 'Sunil Joshi',
    CustomerEmail: 'sunil@gmail.com',
    ProjectName: 'Elite Admin',
    Status: 'Active',
    Photo: "./imgs/avatar3.png",
    Weeks: '11',
    Budget: '$3.9k',
    Location: 'India',
    },
    {
    CustomerID: 1008,
    Name: 'Andrew McDownland',
    CustomerEmail: 'andrew@gmail.com',
    ProjectName: 'Real Homes WP Theme',
    Status: 'Pending',
    Photo: "./imgs/avatar4.jpg",
    Weeks: '19',
    Budget: '$24.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1009,
    Name: 'Christopher Jamil',
    CustomerEmail: 'jamil@gmail.com',
    ProjectName: 'MedicalPro WP Theme',
    Status: 'Completed',
    Photo: "./imgs/avatar.jpg",
    Weeks: '34',
    Budget: '$16.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1010,
    Name: 'Michael',
    CustomerEmail: 'michael@gmail.com',
    ProjectName: 'Weekly WP Theme',
    Status: 'Cancel',
    Photo: "./imgs/avatar2.jpg",
    Weeks: '34',
    Budget: '$16.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1011,
    Name: 'Nirav Joshi',
    CustomerEmail: 'nirav@gmail.com',
    Photo: "./imgs/avatar2.jpg",
    ProjectName: 'Hosting Press HTML',
    Status: 'Active',
    Weeks: '40',
    Budget: '$2.4k',
    Location: 'India',
    },
    {
    CustomerID: 1012,
    Name: 'Sunil Joshi',
    CustomerEmail: 'sunil@gmail.com',
    ProjectName: 'Elite Admin',
    Status: 'Active',
    Photo: "./imgs/avatar3.png",
    Weeks: '11',
    Budget: '$3.9k',
    Location: 'India',
    },
    {
    CustomerID: 1013,
    Name: 'Andrew McDownland',
    CustomerEmail: 'andrew@gmail.com',
    ProjectName: 'Real Homes WP Theme',
    Status: 'Pending',
    Photo: "./imgs/avatar4.jpg",
    Weeks: '19',
    Budget: '$24.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1014,
    Name: 'Christopher Jamil',
    CustomerEmail: 'jamil@gmail.com',
    ProjectName: 'MedicalPro WP Theme',
    Status: 'Completed',
    Photo: "./imgs/avatar.jpg",
    Weeks: '34',
    Budget: '$16.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1015,
    Name: 'Michael',
    CustomerEmail: 'michael@gmail.com',
    ProjectName: 'Weekly WP Theme',
    Status: 'Cancel',
    Photo: "./imgs/avatar2.jpg",
    Weeks: '34',
    Budget: '$16.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1016,
    Name: 'Nirav Joshi',
    CustomerEmail: 'nirav@gmail.com',
    Photo: "./imgs/avatar2.jpg",
    ProjectName: 'Hosting Press HTML',
    Status: 'Active',
    Weeks: '40',
    Budget: '$2.4k',
    Location: 'India',
    },
    {
    CustomerID: 1017,
    Name: 'Sunil Joshi',
    CustomerEmail: 'sunil@gmail.com',
    ProjectName: 'Elite Admin',
    Status: 'Active',
    Photo: "./imgs/avatar3.png",
    Weeks: '11',
    Budget: '$3.9k',
    Location: 'India',
    },
    {
    CustomerID: 1018,
    Name: 'Andrew McDownland',
    CustomerEmail: 'andrew@gmail.com',
    ProjectName: 'Real Homes WP Theme',
    Status: 'Pending',
    Photo: "./imgs/avatar4.jpg",
    Weeks: '19',
    Budget: '$24.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1019,
    Name: 'Christopher Jamil',
    CustomerEmail: 'jamil@gmail.com',
    ProjectName: 'MedicalPro WP Theme',
    Status: 'Completed',
    Photo: "./imgs/avatar.jpg",
    Weeks: '34',
    Budget: '$16.5k',
    Location: 'USA',
    },
    {
    CustomerID: 1020,
    Name: 'Michael',
    CustomerEmail: 'michael@gmail.com',
    ProjectName: 'Weekly WP Theme',
    Status: 'Cancel',
    Photo: "./imgs/avatar2.jpg",
    Weeks: '34',
    Budget: '$16.5k',
    Location: 'USA',
    }
]

