"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Orders", [
      {
        OrderID: 1,
        CustomerID: 1001,
        EmployeeID: 1,
        Item: "Product A",
        TotalAmount: 100.0,
        Status: "Shipped",
        Location: "USA",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        OrderID: 2,
        CustomerID: 1002,
        EmployeeID: 2,
        Item: "Product B",
        TotalAmount: 200.0,
        Status: "Pending",
        Location: "India",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Add more orders here
      {
        OrderID: 3,
        CustomerID: 1003,
        EmployeeID: 3,
        Item: "Product C",
        TotalAmount: 150.0,
        Status: "Processing",
        Location: "USA",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        OrderID: 4,
        CustomerID: 1004,
        EmployeeID: 4,
        Item: "Product D",
        TotalAmount: 300.0,
        Status: "Shipped",
        Location: "Canada",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        OrderID: 5,
        CustomerID: 1005,
        EmployeeID: 5,
        Item: "Product E",
        TotalAmount: 250.0,
        Status: "Delivered",
        Location: "Germany",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        OrderID: 6,
        CustomerID: 1006,
        EmployeeID: 6,
        Item: "Product F",
        TotalAmount: 180.0,
        Status: "Pending",
        Location: "India",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        OrderID: 7,
        CustomerID: 1007,
        EmployeeID: 7,
        Item: "Product G",
        TotalAmount: 210.0,
        Status: "Processing",
        Location: "USA",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        OrderID: 8,
        CustomerID: 1008,
        EmployeeID: 8,
        Item: "Product H",
        TotalAmount: 280.0,
        Status: "Shipped",
        Location: "Canada",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        OrderID: 9,
        CustomerID: 1009,
        EmployeeID: 9,
        Item: "Product I",
        TotalAmount: 320.0,
        Status: "Delivered",
        Location: "Germany",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        OrderID: 10,
        CustomerID: 1010,
        EmployeeID: 10,
        Item: "Product J",
        TotalAmount: 270.0,
        Status: "Pending",
        Location: "India",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Orders", null, {});
  },
};
